### ISSUE TITLE
7.x-1.5 to 7.x-1.6 cross-ports

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/devel#49]
I am assuming that I need to start from 7.x-1.5, since the first release of the Backdrop port claims to have parity with that version: https://github.com/backdrop-contrib/devel/releases/tag/1.x-1.5

- [x] #64 | [dcf7727](http://git.drupalcode.org/project/devel/commit/dcf77278a96b1275cae5866970048f54c19f34ff) | [Remove xhprof integration. Please use xhprof module. Or if you prefer a non-Drupal solution, see xhgui or xhprof.io](http://drupal.org/project/devel/issues/2471058)
- [x] #59 | [1be2fe3](http://git.drupalcode.org/project/devel/commit/1be2fe39a80c55771d2e56adccc141ae9302428a) | [Issue #1919460 by sun, mr.baileys: Fixed Bogus query parameters in devel switch user links.](http://drupal.org/project/devel/issues/1919460)
- [x] #60 | [75f228f](http://git.drupalcode.org/project/devel/commit/75f228f8086f74778e4cc7245b011bfd912dae04) | [Issue #2130357 by vbouchet, upupax: Fixed Drush generate content create empty title.](http://drupal.org/project/devel/issues/2130357)
- [x] #61 | [673ce9e](http://git.drupalcode.org/project/devel/commit/673ce9e0e46ec21fd5e2997fadcafe7f4f6c2b68) | [Issue #2324027 by alberto56: Fixed devel_generate_content_add_node() in devel_generate/devel_generate.inc: wrong @param documentation.](http://drupal.org/project/devel/issues/2324027)
- [x] #62 | [b096916](http://git.drupalcode.org/project/devel/commit/b096916f8a54510eb78871567712a894d3fb19a1) | [Issue #2366797 by salvis: Running dpm()/krumo() on  changes ->user to 1.](http://drupal.org/project/devel/issues/2366797)
- [x] #63 | [9e4a40f](http://git.drupalcode.org/project/devel/commit/9e4a40f8a471302282988d3a6ccfb50db72b4d3d) | [Issue #1858318 by dalin: Make debugging EFQ easier by implementing hook_query_alter()](http://drupal.org/project/devel/issues/1858318)
- [x] #64 | [9d89e71](http://git.drupalcode.org/project/devel/commit/9d89e71e19b57a6c55ee78f4ddc14b9a1b55d9da) | [Issue #2471058 by geerlingguy: Remove the rest of the XHProf integration](http://drupal.org/project/devel/issues/2471058)
- [x] #65 | [d734bda](http://git.drupalcode.org/project/devel/commit/d734bda7dea87c733a0acb2ab0c51e2f5ceaf9d5) | [Issue #2465025 by willzyx: SQL query log doesn't work on pages generated by a view](http://drupal.org/project/devel/issues/2465025)
- [ ] N/A | [953e662](http://git.drupalcode.org/project/devel/commit/953e662c21a15eb39d1d485c0e50adaa4bf4f543) | [Issue #2343269 by david.hughes: JavaScript error while generating menus](http://drupal.org/project/devel/issues/2343269)
- [x] #66 | [566318b](http://git.drupalcode.org/project/devel/commit/566318b758e45e9842a4185db9481eb3c7156620) | [Issue #2429787 by Dave Reid: Fixed file generation should use file_unmanaged_move() instead of file_move() before the file_save() has been called.](http://drupal.org/project/devel/issues/2429787)
- [x] #66 | [98011ab](http://git.drupalcode.org/project/devel/commit/98011abf3da8023e8d4df4d7641cec2d9006d650) | Pass a directory to file_unmanaged_move() instead of the full path. (follow-up to [#2429787](http://drupal.org/project/devel/issues/2429787)
- [x] #67 | [b313536](http://git.drupalcode.org/project/devel/commit/b3135365d77752caedd697ad2734609de51cd299) | [Issue #2594989 by Jacine: devel_krumo_path.js causes request for help.png when not in use](http://drupal.org/project/devel/issues/2594989)
- [x] #68 | [34e948a](http://git.drupalcode.org/project/devel/commit/34e948a20560a997087239893f482d386facd12a) | [Issue #2593435 by Sagar Ramgade: Fix double occurence of "is" in devel_shutdown_real](http://drupal.org/project/devel/issues/2593435)
- [x] #69 | [62d53dd](http://git.drupalcode.org/project/devel/commit/62d53dd3dd1450533daacdb0f70ffa7558d9cbd7) | [Issue #1190074 by simanta, greggles, joachim: Show real arguments instead of placeholders in query log.](http://drupal.org/project/devel/issues/1190074)
- [x] #70 | [0cb3c81](http://git.drupalcode.org/project/devel/commit/0cb3c819eb537727f363aefc5a99e70e98e3055c) | [Issue #2561457 by alan-ps, Jeroen94: Undefined variable "node" in comment_view() on comment/%/devel/render.](http://drupal.org/project/devel/issues/2561457)
- [x] N/A, but see https://github.com/backdrop-contrib/devel/issues/49#issuecomment-508888707 | [66b4095](http://git.drupalcode.org/project/devel/commit/66b409593700194623ed486fed58528ab85a68ec) | [Issue #2653284 by Zoltán Balogh: Remove string concatenation from menu item descriptions.](http://drupal.org/project/devel/issues/2653284)
- [ ] #xx | [8868652](http://git.drupalcode.org/project/devel/commit/8868652ec5f2a1121cf306287f1996dad44f4c27) | [Issue #1918302 by TravisCarden: Remove executable bits from krumo file permissions](http://drupal.org/project/devel/issues/1918302)
- [ ] PR blocked by previous, unmerged changes. See #72#issuecomment-508889461 | [f047d41](http://git.drupalcode.org/project/devel/commit/f047d41e62769c9d9ec917df9648e935d7abc132) | [Issue #2654578 by hey_germano: Add devel_generate property to files and terms created by Devel Generate](http://drupal.org/project/devel/issues/2654578)
- [ ] #xx | [cadea9a](http://git.drupalcode.org/project/devel/commit/cadea9ab0f255e0a58e3b1e6c3e0d368d2ce6763) | [Issue #2381779 by DuaelFr, salvis: Various files in Krumo have incorrect line endings and other white space errors (no functional changes).](http://drupal.org/project/devel/issues/2381779)
- [x] #73 | [196a1eb](http://git.drupalcode.org/project/devel/commit/196a1eb74279b37416d64b30c6d5b54f5d769df7) | [Issue #2381779 by salvis, TravisCarden: Rename Interface.PNG to Interface.png (no functional changes, the file is not actually used).](http://drupal.org/project/devel/issues/2381779)
- [x] #74 | [643407c](http://git.drupalcode.org/project/devel/commit/643407c9c358b3b2b938a03023a2274dbfd67c9e) | [Issue #2559061 by dagmar: Fatal error: Cannot redeclare dd().](http://drupal.org/project/devel/issues/2559061)
- [x] #75 | [de728df](http://git.drupalcode.org/project/devel/commit/de728df33b252cb56cd42655202beb61f458bb8f) | [Issue #927690 by joe_carvajal, Mav-im, torotil: Add support to dsm() and dpm() for protected or private object fields.](http://drupal.org/project/devel/issues/927690)
- [x] #76 | [2f0db7d](http://git.drupalcode.org/project/devel/commit/2f0db7d7dd41af26fdd71033a2c0258a133efef8) | [Issue #2606018 by RoSk0, das-peter: devel_switch_user_form_submit() creates wrong token.](http://drupal.org/project/devel/issues/2606018)
- [ ] N/A | [55ad8ae](http://git.drupalcode.org/project/devel/commit/55ad8aec08413da664c4450e2f3a970976717eed) | [Issue #2879092 by Aron Novak: Generating text - PHP 7.1 warning.](http://drupal.org/project/devel/issues/2879092)
- [ ] N/A | [36151ff](http://git.drupalcode.org/project/devel/commit/36151ffa448ab520b74373a96f693f9f3a403262) | [Issue #2750963 by JvE: Generating field text fails if max length is less than 6.](http://drupal.org/project/devel/issues/2750963)
- [x] #77 | [48def5e](http://git.drupalcode.org/project/devel/commit/48def5e3fee605a707213e41fdf5869032848799) | [Issue #2065225 by maximpodorov: Wrong usage of substr in krumo.](http://drupal.org/project/devel/issues/2065225)
- [ ] N/A, but see https://github.com/backdrop-contrib/devel/issues/49#issuecomment-508888707 | [496880d](http://git.drupalcode.org/project/devel/commit/496880dc719967db8e31b42add5e368258c70a68) | [Issue #1169726 by salvis: Hard-coded links in menu item descriptions makes it impossible to translate them.](http://drupal.org/project/devel/issues/1169726)
- [ ] N/A; see https://github.com/backdrop-contrib/devel/issues/49#issuecomment-508894547 | [8f20578](http://git.drupalcode.org/project/devel/commit/8f20578af2068c02587ba9a664ef411c38569ae2) | [Issue #2394661 by aramboyajyan: Use default Krumo skin when no skin is defined.](http://drupal.org/project/devel/issues/2394661)
- [ ] N/A | [ac84bb1](http://git.drupalcode.org/project/devel/commit/ac84bb17cf164f3125ad7b4442b17c41683ed182) | [Issue #2111127 by jacob.embree, salvis: Fix variable dev_timer, should be named devel_timer.](http://drupal.org/project/devel/issues/2111127)
- [x] #78 | [4edd3d4](http://git.drupalcode.org/project/devel/commit/4edd3d49090748c909d954baeab4ccd67080a8aa) | [Issue #1257584 by jacob.embree, zorya: Devel Variable Editor: Wrap variable names in LABEL tags.](http://drupal.org/project/devel/issues/1257584)
- [x] #79 | [8f86f71](http://git.drupalcode.org/project/devel/commit/8f86f7136b6eeb66af303fe52a5e7b096d0eb9e9) | [Issue #2933660 by jacob.embree, zorya: Include fragment in link to rebuild registry.](http://drupal.org/project/devel/issues/2933660)
- [ ] #xx | [752a1ca](http://git.drupalcode.org/project/devel/commit/752a1ca7adcece537ce9e04e31c056273784b458) | [Issue #2855666 by joseph.olstad, MustangGB, Nick Robillard: Make Krumo compatible with XSS injection protection to drupal_set_message()](http://drupal.org/project/devel/issues/2855666)
- [x] #51 | [991250a](http://git.drupalcode.org/project/devel/commit/991250a48f92cf558dc525e783d74da538d6c294) | [Issue #269984 by jacob.embree, zorya, salvis: Coding standards (comments).](http://drupal.org/project/devel/issues/269984)
- [ ] #xx | [bd4061f](http://git.drupalcode.org/project/devel/commit/bd4061f13916ad38a40d519a90a751db470fa709) | [Issue #2959508 by salvis: Fix PHP 7.2 Incompatibility - count(): Parameter must be an array...](http://drupal.org/project/devel/issues/2959508)
- [ ] #xx | [7fe21b2](http://git.drupalcode.org/project/devel/commit/7fe21b294162796a60225f9d12283d618100a960) | [Issue #2448063 by jacob.embree, zaporylie: Add #actions container to submit buttons](http://drupal.org/project/devel/issues/2448063)
- [ ] #xx | [cbc82b7](http://git.drupalcode.org/project/devel/commit/cbc82b72e4c251c925b790a4e5953a5a317bf759) | [Issue #541342 by zorya, salvis: Display message about Devel block missing because Menu is not enabled.](http://drupal.org/project/devel/issues/541342)

---
`git log 7.x-1.5..7.x-1.6 --reverse --no-merges --pretty=format:"- [ ] #xx | [%h](http://git.drupalcode.org/project/[project_name]/commit/%H) | [%s](http://drupal.org/project/devel/issues/" | sed -E "s/^(.*#)([[:digit:]]*)(.*)$/\1\2\3\2)/g"`

**Comment by klonos** [comment]
Hey @quicksketch 👋 ...the D7 module decided to remove support for XHProf in https://git.drupalcode.org/project/devel/commit/dcf77278a96b1275cae5866970048f54c19f34ff and http://git.drupalcode.org/project/devel/commit/9d89e71e19b57a6c55ee78f4ddc14b9a1b55d9da ...they now recommend using https://www.drupal.org/project/xhprof instead. Do you think we should be doing the same in the Backdrop port, or retain support?

See:

https://www.drupal.org/project/devel/issues/1848378
https://www.drupal.org/project/devel/issues/2166165
https://www.drupal.org/project/devel/issues/2471058

Edit: I've filed a PR for it in case you agree to have it removed: https://github.com/backdrop-contrib/devel/pull/64

**Comment by klonos** [comment]
https://www.drupal.org/project/devel/issues/2653284 | https://git.drupalcode.org/project/devel/commit/66b409593700194623ed486fed58528ab85a68ec is not applicable to us, but that commit implemented "a fix" that was not an actual fix for the problem reported:

> Please, remove the string concatenation from menu item's descriptions, because in this format only the first parts of the strings are translatable.

Instead of moving the URLs inside the strings, they should have used `@` references, and still use `url()`.

Anyway, that commit made it apparent that menu titles and descriptions were not passed through `t()` (so would not be translatable anyway), so I have filed a PR that wraps these in `t()` (and also fixes a few double spaces here and there): https://github.com/backdrop-contrib/devel/pull/71

Edit: same deal with http://drupal.org/project/devel/issues/1169726 and the respective commit in http://git.drupalcode.org/project/devel/commit/496880dc719967db8e31b42add5e368258c70a68

**Comment by klonos** [comment]
I want to mark http://drupal.org/project/devel/issues/2394661 | http://git.drupalcode.org/project/devel/commit/8f20578af2068c02587ba9a664ef411c38569ae2 as N/A, but wondering re this bit:

https://github.com/backdrop-contrib/devel/blob/1.x-1.x/lib/krumo/class.krumo.php#L676

```php
    $css = '';
    // DEVEL: changed for Backdrop config system.
    $skin = config_get('devel.settings', 'krumo_skin');
    if (!$skin) {
      $skin = 'default';
    }
```

I see that we ship the various available skins in https://github.com/backdrop-contrib/devel/tree/1.x-1.x/lib/krumo/skins, but I don't see this `'krumo_skin'` setting in the admin UI in `admin/config/development/devel` (and there is no reference to it in https://github.com/backdrop-contrib/devel/blob/1.x-1.x/devel.admin.inc). Am I missing something?

Edit: ...we seem to have removed this option: https://github.com/backdrop-contrib/devel/commit/8d3d66085407bb8816180a7d4c70923e66d592e5

**Comment by klonos** [comment]
It seems that the 7.x variables `dev_timer` and `dev_mem` have been renamed to `devel_timer` and `devel_mem` respectively at some point. In our devel.install file
