### ISSUE TITLE
7.x-1.6 to 7.x-1.7 cross-ports

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/devel#50]
...follow-up from #49

- [ ] | #xx | [75b6da2](http://git.drupalcode.org/project/devel/commit/75b6da2c54ea5c88056e0e28c793fb37800e6b85) | [Issue #2962943 by ron_s, MustangGB: Multi-level objects/arrays displayed with krumo causes page to never finish loading.](http://drupal.org/project/devel/issues/2962943)
- [ ] | #xx | [b2d0766](http://git.drupalcode.org/project/devel/commit/b2d076623658a117dfbac84e7256a2a1de596516) | [Issue #2987144 by volkswagenchick: Fix README.txt, useful links and formatting.](http://drupal.org/project/devel/issues/2987144)
- [ ] | #xx | [7574843](http://git.drupalcode.org/project/devel/commit/7574843960adb4e7e034d68384447a39badca12c) | [Issue #3030890 by solideogloria: Fix Krumo's <big> tag is not HTML5 compliant.](http://drupal.org/project/devel/issues/3030890)
- [ ] | #xx | [57e32c6](http://git.drupalcode.org/project/devel/commit/57e32c63089216da92efe811212bd4f6026ba307) | [Issue #2411615 by willzyx, salvis: Fix CSRF vulnerabilities 'Run cron' and 'Clear cache' in menu callbacks.](http://drupal.org/project/devel/issues/2411615)

---
`git log 7.x-1.6..7.x-1.7 --reverse --no-merges --pretty=format:"- [ ] #xx | [%h](http://git.drupalcode.org/project/[project_name]/commit/%H) | [%s](http://drupal.org/project/devel/issues/" | sed -E "s/^(.*#)([[:digit:]]*)(.*)$/\1\2\3\2)/g"`
